rdar://60088322 p27418106 OPS/COR Xmas patch. Only purge repaired tombstones.
Xmas/Festive patch.  Track last successful repair times and use
them to make decions about when it is safe to drop tombstones
without risking data resurrection on retrieval or repairs.

CIE 3.0 Commits / Radars

838850a97440ca01c3cfce7e3b81d83507aa6fff <rdar://problem/27418106
heavily modified due to changes from transient replica and
internode messaging rewrite.

c594e8232ea01ac9dd038b9452861d4b2276ab83  <rdar://problem/31332689>
During startup, SystemKeyspace.getLastSuccessfulRepair should (#743)
call getColumnFamilyStoreIncludingIndexes() to properly handle schemas
using 2i. *only cherry-picked test*,
change to SystemKeyspace is not needed to make it pass (same on CIE 3.0.x branch)

Reintroduced getColumnFamilyStoreIncludingIndexes, lookups
by index names were failing as that does not happen on OSS trunk
because SystemKeyspaceTest.testReadingAllLastSuccessfulRepairs
does not include indices.

cdc94fea82e9670168cc875661d1aad1898810b5  <rdar://problem/33294888>
Cass: AssertionError in force compact for wrapping token ranges (#885)
p33294888> BUG? Unwrap overlapped forced compaction ranges
Refactor for View.sstablesInBounds changes.

633d18c1a1d93dece7ebcbc889a38f21aae55107  <rdar://problem/32577145>
Don't bump last repair time in Christmas patch for preview repair

881b4d8f620e348613a41e8149b36369019be9f2  <rdar://problem/32748059>
Range serialization for repair history does not respect ByteBuffer bounds (#853) XMAS PATCH

p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - fixup bytesToHex

cleanroom: fixup error in bytesToHex

p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - xmas patch data lost on startup

d91c203bbc7568774abd939db0383eddf36719f2  <rdar://problem/33549530>
Token serialization differences cause xmas patch data to be lost on startup (#896)

05c33833b53c065e78de6c2f43c1b79f4723aabf  <rdar://problem/33810719>
IR: sync repair history (#902), refactored for internode messaging changes.

f81448bd0b538c1084321ef8200f98dbac5508f6
Don't delete incremental repair sessions if they still have sstables (#918)
Patch by Blake Eggleston; reviewed by Marcus Eriksson for
CASSANDRA-13758

832a417622e69daf8f9cc5c40c66d4bf343bfc81  <rdar://problem/34065418>
fail preview repair validation if sstables are pending repair / or repair success is received during preview validation (#925)

2f71e6223d7fb74e6f6bbba1011e43ba816a54f5  <rdar://problem/34551446>
Ref leak in CM.getSSTablesToValidate (#937)

2e195ed6c723c7682671bf38d1b8ea1143d1ec9f  <rdar://problem/34942194>
Compaction could resurrect data if it's racing with a repair with christmas patch enabled (#951)  XMAS
* snapshot repair history before compaction and range queries
* unmark sstables as compacting manually after test
* fix tombstonesTest - the fallbackGcBefore should be used directly - it is already calculated gcBefore

ba23f2168ea020c843e038336e30879ecc3a6fef  <rdar://problem/35372014>
Cass: force repair fails, can't do host replacement (#975)

afe39e76b63224d2c1749194a84eeccb4873d33b  <rdar://problem/36057821>
Cass: repairhistorytask logger incorrectly prints anonymous inner class (#991)

p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - repair hist ttl/compaction

e55085c7eb78716fffd1814d4d549a8693de9593
Patch from CASSANDRA-12701 - add TTL and TWCS to repair history tables

08ca61b17c73d2a7cf35bec954390ad626e2f868 properly set TWCS compaction params

c7f59380b51465252e9c8db2047a3a49b983056f  <rdar://problem/37709781>
repair history sync sending out of date values (#1029)

b5f8b685eea94f0cdc467b3b884ef433a121ab01  <rdar://problem/38792008>
Fallback GC Before is not now  XMAS

32f867a01378b3fb686f89a89f344d4b74a6bf20  <rdar://problem/39425813>
Nodetool refresh violates last repair time patch, refactored for
SSTableImport changes.

8fa2315a44d84dc67590bfcf580bd69f2ca4b86f  <rdar://problem/41267382>
Fix to christmas patch internalStatement cache leak (#1134)

5948594d16b62917768aac88a1397b3d4801dbc2  <rdar://problem/40147770>
running repair with Force still updates last repair time in 3.0
don't update last repair time if we skipped some replicas

20a7797904276d791e180c20354894a2ed919feb  <rdar://problem/40147770>
address Marcus's comment making variable reflect allReplicas notion exactly again
unning repair with Force still updates last repair time in 3.0

b648e441a632d3cf2574c8c4ea1f4ec7494d6c84  <rdar://problem/40370261>
RepairSuccess is being sent to repair coordinator twice (#1116)

bd29c98ac0affd7236b387ce5ffc5e14c1df5974  <rdar://problem/56987837>
When repair times out calling syncRepairHistory workflows hangs forever (#1419)
Updated for messaging refactor and change to timeout message string in the test.

dec1f5d3cc0f08b9ff7281447b4ef77af6d8496a  <rdar://problem/57423903>
xmas patch: avoid using the wrong last repair time when checking for fully droppable sstables

aa04b66adce80d653303b3e7809fe8eef35e58a5  <rdar://problem/57472637>
xmas patch: find minimal set of ranges that cover the sstable when checking if it is fully expired & droppable

CIE4 Initial review Fixes
 32ade93714 remove pending sstable check post CASSANDRA-15553
 e2e7475dc5 fully expired sstables should check xmas patch
 8e11369efe minor cleanups
 415664b891 Add a test making sure that the new garbage collection compaction honors xmas patch
 2b01c79c87 remove outdated test
 3fd2980b38 fix RepairJobTest.testOptimizedCreateStandardSyncTasks
 77f1d6ac72 fixup: merge candidate review feedback

(rebased-with-history from commit 4dfcd88a63b82965c9fafda0bf7454341c6cb310)

(rebased-with-history from commit 7ba8eb0205d2cc90f22c30563ad2af89ff8de6a3)

(rebased-with-history from commit d0ee802b8e1a194c7c3e790df1650e6fd370e389)

Squashed rdar://62556116 (AssertionError in Message.out when invoked by UpdateRepairedRangesVerbHandler.doVerb during bootstrap)

Use Message#internalResponse which is purpose-built for this sort of reply instead of
Message#out which is meant for requests.

(rebased-with-history from commit 718471866424234ca897629e02727db567300b10)

(rebased-with-history from commit a6d2aa53b97bbba07d03079dcc2399314f019d27)

Squashed Fix the verbs and add test

With the previous fix we got NPE since INTERNAL_RSP has a null serializer. Removed the
UpdateRepairedRangesResponse and instead consider a reply a success (we only ever set the
boolean there to true anyway).

Also the APPLE_REPAIRED_RANGES request was broken, not replying correctly.

(rebased-with-history from commit 11bec5f2ac6f8d0eebfe81035e9c5e10d401e4bf)

(rebased-with-history from commit f8ea75fb9bced955f01526b431c74ed791915d50)

Squashed Add support for adding custom Verbs

Patch by marcuse; reviewed by Benedict Elliott Smith and David Capwell for CASSANDRA-15725

(rebased-with-history from commit c0c2fbe75143d40b2265d270d449151c45e64ade)

(rebased-with-history from commit 7864b85d2dd5a7ab8aefe6a35d09605f5f5fa869)

(rebased-with-history from commit 843e123513f89e50b55f47dd3aea69197d4426a2)

(rebased-with-history from commit 4e3ba39172bfeaeb7251ae28e237f0ab71ca7d05)

(rebased-with-history from commit dbf79c74a0c9f2245b7fc7a48b4614edcdf56115)

(rebased-with-history from commit 153cb2cbbbd2b7a3e842e74ad8e4b844ac00aa8f)

<rdar://65940886> fixup (original rdar://27418106) OPS/COR Xmas patch… (#1808)

Mistake in forward porting commit b648e441a632d3cf2574c8c4ea1f4ec7494d6c84
<rdar://problem/40370261> RepairSuccess is being sent to repair coordinator twice (#1116)

The forward port did not remove the local call to directly update the last repaired time,
so it was handled locally and when receiving the last repair update time message as the coordinator.

(rebased-with-history from commit e69d4999b4e71d581ec8061c75fc8e8a02e896da)

(rebased-with-history from commit 5187b51700484b4231faffb87eb7fa44b038f8b3)

(rebased-with-history from commit 6eedb6b97bdd98a1b512d99209100b6b8859eb7e)

make sure the SSTableReader instances generated in ChristmasPatchTest have different generation numbers

rdar://66642434 (CIE4 Host replacement bootstrap node crashes on startup after receiving last repair info before loading repairs) (#1822)

Update distributed ChristmasPatchTest to verify restarting re-populates after dtest stop/start.
Factor out loading repair history, move loading before bootrap takes place to match 3.0

Fixes error when replacing a host in a 4.0 cluster.
```
java.lang.IllegalStateException: Last Successful repair should be empty. Org.apache.cassandra.db.xmas.SuccessfulRepairTimeHolder@1ac4579f
        at org.apache.cassandra.db.ColumnFamilyStore.setLastSuccessfulRepairs(ColumnFamilyStore.java:1648) ~[cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.db.ColumnFamilyStore.loadLastSuccessfulRepair(ColumnFamilyStore.java:1627) ~[cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:394) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:659) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:776) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
```

Update the in-jvm Dtest to have the Instance load the repair history after enabling ActiveRepair like regular startup.

(rebased-with-history from commit 5c9b0ca0b0385b7d8db1c854e7c3010c6841cfa4)

(rebased-with-history from commit db9099c2c4d80ec22a9b2386ad6e43a30d42bb92)

(rebased-with-history from commit 52f5c1d896fc9895427525a580b91da52e20b87d)

<rdar://problem/66915547> Fix REPAIR_HISTORY{,_INVALIDATION}_CF missing from SystemKeyspace.ALL_TABLE_NAMES (#1857)

(rebased-with-history from commit a4050b4d8f1e2788dfcc3e02559474c1c635b1c7)

(rebased-with-history from commit f0937b251e45229b7f53579cd3d68b319a229e73)

(rebased-with-history from commit 2adac871ab5aba503b04e00e25c2ea0375d7aa23)

<rdar://problem/58917305> Reduce the amount of logging from RepairHistorySyncTask (#1725) (#1856)

(rebased-with-history from commit 258f905d6e05de33ad3e5474588e7df013bd2464)

(rebased-with-history from commit c12bb37e5a8e911df035291b0b4524232a67c2e0)

(rebased-with-history from commit 00b57d1dbfc166681b26fe296af7490e720b50cc)

rdar://66933802 (forward port rdar://60101151) Ensure current key for purger is set before applying repair tracking transform (#1870)

Forward port <rdar://problem/60101151> istshared21dev : java.lang.NullPointerException during read

* Repaired data tracking tests run with xmas patch enabled and disabled
* Set purger current key before applying transform

CIE4.0 port moved the test table from CF2 to CF6 to have the caching setup the same.

Co-authored-by: Sam Tunnicliffe <samt@apple.com>

(rebased-with-history from commit d1cd165660f3efe4a879897a89836558b1e9f48b)

(rebased-with-history from commit 824434089a18874d4f5dff345d59c8c25edabd91)

(rebased-with-history from commit f7f20c52f223c2f5e26ed75195729145c2261140)

<rdar://problem/67940452> Exception during repair history sync (#1881)

(rebased-with-history from commit 611a4c2f29562e7b5bd39560032482962cb50f85)

(rebased-with-history from commit 8ba30481a242ca6b51cd7fec2fe3398d635a75c5)

(rebased-with-history from commit c676dd71540f8ddb7663bab80f9fb7f47b5f27d2)

rdar://69866491 (Enable Christmas patch by default) (#1949) (#1950) (#1951)

<rdar://problem/62984534> fix "Cannot service reads while bootstrapping" (#1893)

Run fetchRepairedRanges on the completion of bootstrapStreamFuture together as a chained future, instead of running it as a callback. Therefore, storage service bootstrap blocks until the completion of fetchRepairedRanges.

(rebased-with-history from commit f1f15f1bda439b418ff869f4ad7477ecdacf3e1a)

(rebased-with-history from commit b42888634e322f946229d0c9e424d963b8f0cf22)

fixup: rdar://60088322 p27418106 OPS/COR Xmas patch. Only purge repaired tombstones. ChristmasPatchTest/PreviewRepairTest fixes and cleanups

fixup: rdar://60088322 p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - ignore unrepaired keyspaces

(rebased-with-history from commit cdd2e75055b4ebab44fecedfc29bce3e8ce0422a)

(rebased-with-history from commit 348f12ea9f515d88733b20f3d9dbdb720015ac4d)

(rebased-with-history from commit fb18e0bf52eb0bf98b910f80e22c8d87a01ac905)

(rebased-with-history from commit ea32040b21553c9f0b246e5754add582e736d37e)

fixup  rdar://60088322 p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - add-opens for java.desktop

Intermittendly hit on Rio and in IntelliJ.  https://quality.pie.apple.com/#/configurations/cie-cassandra-ghprb-cie-cassandra-400-prb-unit-tests/runs/526/features/unit.java=11.org.apache.cassandra.repair/scenarios/org.apache.cassandra.repair.RepairJobTest/steps/testNoTreesRetainedAfterDifference

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object com.sun.beans.introspect.ClassInfo.mutex accessible: module java.desktop does not "opens com.sun.beans.introspect" To unnamed module @40f70521
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
        at org.github.jamm.MemoryMeter.addFieldChildren(MemoryMeter.java:330)
        at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:269)
        at org.apache.cassandra.utils.ObjectSizes.measureDeep(ObjectSizes.java:155)
        at org.apache.cassandra.repair.RepairJobTest.testNoTreesRetainedAfterDifference(RepairJobTest.java:273)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

(rebased-with-history from commit 325034c3e51bc1397932432c931b1a2f04ef1d22)

fixup rdar://60088322 p27418106 OPS/COR Xmas patch. Only purge repaired tombstones - add-opens for jdk.management.jfr/jdk.management.jfr

Failing with
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final jdk.management.jfr.StreamManager jdk.management.jfr.FlightRecorderMXBeanImpl.streamHandler accessible: module jdk.management.jfr does not "opens jdk.management.jfr" to unnamed module @40f70521
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at org.github.jamm.MemoryMeter.addFieldChildren(MemoryMeter.java:330)
	at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:269)
	at org.apache.cassandra.utils.ObjectSizes.measureDeep(ObjectSizes.java:155)
	at org.apache.cassandra.repair.RepairJobTest.testNoTreesRetainedAfterDifference(RepairJobTest.java:273)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

(rebased-with-history from commit d6bcf09bc275f82faf3e027a66e33a2e9ff80210)

(rebased-with-history from commit b09848fccab9a55511074debf17ea040141028a5)

(rebased-with-history from commit 661520f08ce5211a9f93156441040fad683483f7)

<rdar://problem/59313829> Cancel all ongoing preview repair sessions when we receive conflicting RepairSuccess (#1496) (#1855)

(rebased-with-history from commit 60c443ba2cfa0201f1a1831f2e0fe5f71343e065)

(rebased-with-history from commit 746b41ac818f17fa8e80d840814b556918bf6b7a)

(rebased-with-history from commit e36412a36ef1702d84c70ed6ec079dffe7b25e82)

(rebased-with-history from commit a28492f9032df638a36134a95c5de68bdbc2460f)

fixup: <rdar://problem/59313829> Cancel all ongoing preview repair sessions when we receive conflicting RepairSuccess (#1496) (#1855) - correct option arguments and avoid uncaught exceptions

(rebased-with-history from commit 3baff0fb4030116c7ae0755a9bd66a0dd86808ec)

(rebased-with-history from commit e922187c80b26f10630eab2724d7f6a74ce97885)

(rebased-with-history from commit ec4298f0b41f04cdc1c589f25337ca81a89e7355)

(rebased-with-history from commit 4d2e1d488cef4c8ac827f1cb9a383f7d21cacc12)

(rebased-with-history from commit a2052a8a3397a7d6886fa56aaf3d14efbcd19b75)

(rebased-with-history from commit 3de0168548577c470c01a3167e177b1960cb2458)

Snapshots for repaired data mismatch include repair history (#2004)

rdar://70201623 (Diagnostic snapshots for repaired data mismatch should include repair history)

(rebased-with-history from commit 4858381937ace6f7249ded65825ebdd7a8220c8b)

(rebased-with-history from commit 67dbfa2422ce0e6c2ff17a9cbde8afba6b8413b5)

(rebased-with-history from commit 90b1962a41d6c51a923d5318d0f3abe1f9753173)

(rebased-with-history from commit b24dec7c9a7cdf2f036857f05905ff9cbd59a93a)

(rebased-with-history from commit 0dc427aacab9c7694e0365ee966bd75978b1e770)

(rebased-with-history from commit 40ef0f35d487d3517162bee2a5ed91263d0c50fd)

rdar://77857547 ([IF1 Issue] xmas patch SuccessfulRepairTimeHolder#getFullyRepairedTimeFor allocates a lot of memory causing GC issues impacting users) (#2393)

(rebased-with-history from commit c566fe8af34103a58b2935327c096c2a10b6a72f)

rdar://79964001 (4.0: port 3.0.24 xmas patch improvements) (#2484)

* Remove xmas patch list iterators

* rdar://78245560 (Reduce the amount of work in SuccessfulRepairTimeHolder.getFullyRepairedTimeFor) (#2406)

* 4.0.0: <rdar://problem/63443958> xmas patch: clean up system.repair_history … (#2138)