rdar://66642434 (CIE4 Host replacement bootstrap node crashes on startup after receiving last repair info before loading repairs) (#1822)
Update distributed ChristmasPatchTest to verify restarting re-populates after dtest stop/start.
Factor out loading repair history, move loading before bootrap takes place to match 3.0

Fixes error when replacing a host in a 4.0 cluster.
```
java.lang.IllegalStateException: Last Successful repair should be empty. Org.apache.cassandra.db.xmas.SuccessfulRepairTimeHolder@1ac4579f
        at org.apache.cassandra.db.ColumnFamilyStore.setLastSuccessfulRepairs(ColumnFamilyStore.java:1648) ~[cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.db.ColumnFamilyStore.loadLastSuccessfulRepair(ColumnFamilyStore.java:1627) ~[cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:394) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:659) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:776) [cie-cassandra-4.0.0.1.jar:4.0.0.1]
```

Update the in-jvm Dtest to have the Instance load the repair history after enabling ActiveRepair like regular startup.

(rebased-with-history from commit 5c9b0ca0b0385b7d8db1c854e7c3010c6841cfa4)

(rebased-with-history from commit db9099c2c4d80ec22a9b2386ad6e43a30d42bb92)